# Generated by Django 5.2.12 on 2026-03-06 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('beginner', "Boshlang'ich"), ('middle', "O'rta"), ('advanced', 'Yuqori')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('students_count', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('category', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('skills', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.instructor')),
            ],
        ),
    ]
